spring:
  datasource:
    url: jdbc:mysql://localhost:3306/atm_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 3698741ken
